#!/bin/bash
#
#SBATCH --job-name=CHOCO_SES-2_pt1
#SBATCH -N 2
#SBATCH -c 1
#SBATCH -t 2:00:00
#SBATCH --mem-per-cpu 75000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/bbx/derivatives/error_logs/feat3_%a_ses-1_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/bbx/derivatives/error_logs/feat1_%a_ses-1_err.txt


/projects/niblab/modules/software/fsl/5.0.10/bin/feat /projects/niblab/bids_projects/Experiments/bbx/derivatives/group_ana/cope${SLURM_ARRAY_TASK_ID}_ses-1.fsf