#!/bin/bash
#
#SBATCH --job-name=F1_bx_s2
#SBATCH -N 4
#SBATCH -c 2
#SBATCH -t 2:00:00
#SBATCH --mem-per-cpu 50000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/bbx/feat1_%A_%a_ses-1_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/bbx/feat1_%A_%a_ses-1_err.txt

/projects/niblab/modules/software/fsl/5.0.10/bin/feat \
/projects/niblab/bids_projects/Experiments/bbx/derivatives/sub-00${SLURM_ARRAY_TASK_ID}/ses-1/func/Analysis/sub-00${SLURM_ARRAY_TASK_ID}*.fsf
