#!/bin/bash
#
#SBATCH --job-name=BBX_ses-2
#SBATCH -N 2
#SBATCH -c 1
#SBATCH -t 1:00:00
#SBATCH --mem-per-cpu 75000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/BBx/feat2_%A_%a_ses-1_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/BBx/feat2_%A_%a_ses-1_err.txt

/projects/niblab/modules/software/fsl/5.0.10/bin/feat /projects/niblab/bids_projects/Experiments/bbx/derivatives/sub-00${SLURM_ARRAY_TASK_ID}/ses-2/func/Analysis/feat2/sub-00${SLURM_ARRAY_TASK_ID}*.fsf
