#!/bin/bash
#
#SBATCH --job-name=CHOCO_SES-2_pt1
#SBATCH -N 2
#SBATCH -c 1
#SBATCH -t 2:00:00
#SBATCH --mem-per-cpu 75000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/EricData/data/derivatives/error_logs/feat1_%A_%a_ses-2_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/EricData/data/derivatives/error_logs/feat1_%A_%a_ses-2_err.txt

subject="sub-00${SLURM_ARRAY_TASK_ID}"
cd /projects/niblab/bids_projects/Experiments/EricData/data/derivatives/${subject}/ses-2/func/Analysis
fsfs=(*.fsf)
for file in ${fsfs[@]}; do
  /projects/niblab/modules/software/fsl/5.0.10/bin/feat /projects/niblab/bids_projects/Experiments/EricData/data/derivatives/${subject}/ses-2/func/Analysis/${file}
done 
