#!/bin/bash
#
#SBATCH --job-name=BBX_fprep
#SBATCH -N 4
#SBATCH -c 2
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu 75000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/bbx/%A_%a_ses-1_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/bbx/%A_%a_ses-1_err.txt

id="sub-0${SLURM_ARRAY_TASK_ID}"
export id
bash /projects/niblab/bids_projects/Experiments/bbx/scripts/fprep_bbx.sh
