#!/bin/bash
#
#SBATCH --job-name=CHOCO_SES-2_pt1
#SBATCH -N 4
#SBATCH -c 2
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu 75000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/EricData/data/derivatives/error_logs/feat1_%A_%a_ses-2_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/EricData/data/derivatives/error_logs/feat1_%A_%a_ses-2_err.txt

module load /home/nbytes/modules/modulefiles/fsl/5.0.10

/projects/niblab/modules/software/fsl/5.0.10/bin/feat /projects/niblab/bids_projects/Experiments/EricData/data/derivatives/sub-0${SLURM_ARRAY_TASK_ID}/ses-2/func/Analysis/sub-0${SLURM_ARRAY_TASK_ID}_ses-2_task-milkshake*_no_reg.fsf
