#!/bin/bash
#
#SBATCH --job-name=BEV_F2_B
#SBATCH -N 2
#SBATCH -c 1
#SBATCH -t 1:00:00
#SBATCH --mem-per-cpu 75000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/Bevel/data/feat2_%A_%a_B_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/Bevel/data/feat2_%A_%a_B_err.txt

/projects/niblab/modules/software/fsl/5.0.10/bin/feat /projects/niblab/bids_projects/Experiments/Bevel/data/derivatives/sub-0${SLURM_ARRAY_TASK_ID}/func/Analysis/feat2/sub-0${SLURM_ARRAY_TASK_ID}*.fsf
